# database init, supports mysql too
database=h2
spring.sql.init.schema-locations=classpath*:db/${database}/schema.sql
spring.sql.init.data-locations=classpath*:db/${database}/data.sql

# Web
spring.thymeleaf.mode=HTML

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
spring.jpa.properties.hibernate.default_batch_fetch_size=16

# Internationalization
spring.messages.basename=messages/messages

# Actuator
management.endpoints.web.exposure.include=*

# Logging
logging.level.org.springframework=INFO

# Maximum time static resources should be cached
spring.web.resources.cache.cachecontrol.max-age=12h

# OpenTelemetry - Auto instrumentation via Java agent
otel.service.name=petclinic
otel.service.version=4.0.0-SNAPSHOT
otel.exporter.otlp.endpoint=https://<your-apm-server>.apm.elastic.cloud:443
otel.exporter.otlp.headers=Authorization=Bearer <your-secret-token>
otel.exporter.otlp.protocol=grpc
otel.metrics.exporter=none
otel.logs.exporter=none
otel.propagators=tracecontext,baggage
